### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by kojq** [kojq/bemela#3]
- [ ] clean up method and file names
- [ ] create an algorithms spec sheet
- [ ] complete Bash scripts
- [ ] add optimizations and language configs
- [ ] implement more algorithms
